### PR TITLE
Switch to rust-based generation and add additional message types

### PR DESCRIPTION
**Pull request by jpbusch**
#### Change default code-generation from py to rust
- py code-generation is replaced by rust-based one (CI, vscode launch config and README)
- py code-generation files are still located in [codegen-py](https://github.com/ika-rwth-aachen/etsi_its_messages/tree/main/utils/codegen/codegen-py)

#### Updates CAM and DENM
- CAM and DENM c-code, msgs and conversion headers are regenerated using the rust-codegen
- this leads to small changes in these generated files, including license updates, line breaks and some small naming changes, because of camel-case / snake-case conversion ([example diff](https://github.com/ika-rwth-aachen/etsi_its_messages/pull/20/files#diff-5caade64bfc998d375f829982064b7eb288c16c893216a49b4373fec07accbb3R36))

#### CPM v2.1.1
- generate c-code / msgs / conversion headers for CPM as a new message type
- add [publish_cpm.py](https://github.com/ika-rwth-aachen/etsi_its_messages/blob/main/utils/scripts/publish_cpm.py) to generate a dummy CPM ROS message
- currently there are no access functions implemented for the CPM

### CODE REVIEW

**Comment by jpbusch** [comment]
We were able to generate and compile the ROS msgs and conversion headers for the CPM. The conversion node is now also able to convert CPMs. Feel free to try out this branch with your use cases. This would help us to validate.

@riebl, @v0-e, @foxei, @lheg

**Comment by joaomiguelpereiradealmeida** [comment]
> We were able to generate and compile the ROS msgs and conversion headers for the CPM. The conversion node is now also able to convert CPMs. Feel free to try out this branch with your use cases. This would help us to validate.
> 
> @riebl, @v0-e, @Foxei, @lheg

Dear @jpbusch , thank you very much for the CPM integration. Since CPMs use CDD Release 2, it would be great if we can also have the [CAM](https://forge.etsi.org/rep/ITS/asn1/cam_ts103900) and [DENM](https://forge.etsi.org/rep/ITS/asn1/denm_ts103831/-/tree/release2) Release 2 available to test the 3 types of messages together. Do you think they could be integrated in this PR?

**Comment by jpbusch** [comment]
Hi @joaomiguelpereiradealmeida! We have decided to only add the CPM with this PR for now. We then want to add a second branch in this repo, on which we will also upgrade CAM and DENM to release2.
Outcome after first tests: The CAM release2 should work quite straight forward, but there will still be a few problems with the DENM release2.

**Comment by joaomiguelpereiradealmeida** [comment]
> Hi @joaomiguelpereiradealmeida! We have decided to only add the CPM with this PR for now. We then want to add a second branch in this repo, on which we will also upgrade CAM and DENM to release2. Outcome after first tests: The CAM release2 should work quite straight forward, but there will still be a few problems with the DENM release2.

Great, thank you @jpbusch. Just a note, I would say that maybe it could be useful to have message conversion from both releases available simultaneously, since in a real-world scenario we are going to have co-existence of vehicles transmitting messages from different releases. So, maybe having different folders on the same branch, e.g. for CAM_r1 and CAM_r2, could work?

**Review by lreiher — APPROVED** [review]

**Pull request merged**
